languageCode = "en-us"
title = "Gao's reading notes"
baseURL = "https://gaow.github.io/reading/"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Author of the site, will be used in meta information
  author = "Gao Wang"
  # Description of the site, will be used in meta information
  description = "Reading list on genetics and computational biology"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
  # cdnjs hosted version; empty string to disable mathjax
  mathjax = "2.7.2" 

[blackfriday]
  latexDashes = true