languageCode = "en-us"
title = "Genetic Analysis Software | The Rockefeller List"
baseURL = "https://gaow.github.io/genetic-analysis-software/"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Author of the site, will be used in meta information
  author = "Gao Wang"
  # Description of the site, will be used in meta information
  description = "Statistical Genetics Analysis Software"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"